name: craft-market-3d

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - mongodb_data_container:/data/db

  redis:
    container_name: redis
    image: bitnami/redis:latest
    ports:
      - '6379:6379'
    environment:
      ALLOW_EMPTY_PASSWORD: yes
      # REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
    volumes:
      - redis_data_container:/bitnami/redis/data
volumes:
  mongodb_data_container:
  redis_data_container:
